---
title: "KNN_GENRES"
author: "Whitney Chu"
date: "24/11/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#import data
```{r}
library(datasets)
library(class)
library(tidyr)
library(tidyverse)    
library(e1071)  
library(RColorBrewer)
library(dplyr)
library(caTools)
library(reshape2)
library(ggplot2)
library(stringr)
library(DMwR)
library(mltools)
library(rmarkdown)
library(rpart)
library(rpart.plot)
library(caret)
library(ggcorrplot)
```

#Read and import data
```{r}
movie.data <- read.csv("IMDb_movies.csv")
movie.data
```

#Preview the Dataset
```{r}
set.seed(100)
movie.data <- movie.data[sample(nrow(movie.data), 2500),]
movie.data <- movie.data[,c(6:8,14)]
movie.data
head(movie.data)
summary(movie.data)
dim(movie.data)
str(movie.data)

movie.data1 <- movie.data
```

#check for missing data
```{r}
colSums(is.na(movie.data))
```

#convert categorical variables
```{r}
movie.data$genre1 <- as.numeric(as.factor(movie.data$genre1))
movie.data$genre2 <- as.numeric(as.factor(movie.data$genre2))
movie.data$genre3 <- as.numeric(as.factor(movie.data$genre3))
movie.data
```

#split into training and testing set 
```{r}
nrow(movie.data)
rows <- c(1:nrow(movie.data))
split <- sample(rows,size = (nrow(movie.data)*0.80))
train <- as.data.frame(movie.data[split,])
test <- as.data.frame(movie.data[-split,])
nrow(train)
head(train)
nrow(test)
head(test)
```

#build the KNN network
```{r}
# Empty variables
pred <- list()
accuracy <- numeric()

# From k=1 to k=100...
for(k in 1:100){
  
  # KnnTestPrediction for each k
  pred[[k]] <- knn(train[,1:3], test[,1:3], train$avg_vote, k, prob=TRUE)
  
  # Accuracy for each k   
  accuracy[k] <- sum(pred[[k]]==test$avg_vote)/length(test$avg_vote)*100
  print(cat(as.character(k) , as.character(accuracy[k])))
}

#find optimal k
index<-which(accuracy %in% max(accuracy))
index


# Accuracy vs Choice of k
?plot
plot(accuracy, type="b", col="dodgerblue", 
     xlab="k, number of neighbors", ylab="Classification accuracy", 
     main="Accuracy vs Neighbors")

# Add lines indicating k with best accuracy
abline(v=which(accuracy==max(accuracy)), col="orange", lwd=1.5)

# Add line for max accuracy seen
?abline
abline(h=max(accuracy), col="red", lty=2)
# lty=2 for dashed

# Add line for min accuracy seen 
abline(h=min(accuracy), col="grey", lty=2)
k <- knn(train = train[,1:3], test = test[,1:3], cl = train$avg_vote, k=index)
k <- as.data.frame(k)
```

#predict and get error
```{r}
k<- as.data.frame(k)
test <- as.data.frame(test)

#pred <- predict(k1, test[,7])
pred<-as.numeric(as.numeric(as.character(sub("," , ".", unlist(k)))))

results2<- data.frame(actual = test$avg_vote, prediction = pred)
results2
paste("RMSE =",RMSE(test$avg_vote, pred))
```

#Print first row
```{r}
newtest<- test[1,1:3]
newtest
```

#Iterate all the possibilites
```{r}
for (q in 1:as.numeric(max(movie.data$genre1))){
  for (j in 1:as.numeric(max(movie.data$genre2))){
    for (x in 1:as.numeric(max(movie.data$genre3))){
      newtest[nrow(newtest) + 1,] = list(q,j,x)
    }
  }
}
```

#predict and order results in descending order
```{r}
k1 <- knn(train = train[,1:3], test = newtest[,1:3], cl = train$avg_vote, k=index)
k1 <- as.data.frame(k1)
k1<- as.data.frame(k1)
test <- as.data.frame(test)


#pred <- predict(k1, test[,7])
pred<-as.numeric(as.numeric(as.character(sub("," , ".", unlist(k1)))))

a<-data.frame(newtest[,1:3],pred)
a
qw<- a[order(a$pred,decreasing = TRUE),][-1,]
qw
```

#convert factors back to characters
```{r}
getStringGenres <- function(row) {
  #make genres numeric
  g1num <- as.numeric(row$genre1[1])
  g2num <- as.numeric(row$genre2[1])
  g3num <- as.numeric(row$genre3[1])
  
  #look in genre 1 in factored movie data table
  #store the index number
  #look back at genre 1 in original data table
  #print out character genre for that index
  index<-movie.data[which(movie.data[,"genre1"]==g1num),][1,0]
  index<-toString(as.numeric(row.names((index))))
  g1Label <- movie.data1[index,1]
  
  #look in genre 2 in factored movie data table
  index<-movie.data[which(movie.data[,"genre2"]==g2num),][1,0]
  index<-toString(as.numeric(row.names((index))))
  g2Label <- movie.data1[index,2]
  
  #look in genre 3 in factored movie data table
  index<-movie.data[which(movie.data[,"genre3"]==g3num),][1,0]
  index<-toString(as.numeric(row.names((index))))
  g3Label <- movie.data1[index,3]
  
  #returns three genres into a list
  return <- list(g1Label,g2Label,g3Label)
}
```

#Top 10 combinations of movie genres
```{r}
topLabels<- test[1,1:3]

for (i in 1:10){
  labels<- getStringGenres(qw[i,])
  topLabels[nrow(topLabels) + 1,] = labels
}
#top 10 
topLabels[-1,]
```