---
title: "KNN_MOVIEPROJECT"
author: "Whitney Chu"
date: "24/11/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#import data
```{r}
library(datasets)
library(class)
library(tidyr)
library(tidyverse)    
library(e1071)  
library(RColorBrewer)
library(dplyr)
library(caTools)
library(reshape2)
library(ggplot2)
library(stringr)
library(DMwR)
library(mltools)
library(rmarkdown)
library(rpart)
library(rpart.plot)
library(caret)
library(ggcorrplot)
```

#Read and import data
```{r}
movie.data <- read.csv("IMDb_movies.csv")
movie.data
```

#Preview the Dataset
```{r}
set.seed(100)
movie.data <- movie.data[sample(nrow(movie.data), 2500),]
movie.data <- movie.data[,c(3:4,6:8,12,14)]
movie.data
head(movie.data)
summary(movie.data)
dim(movie.data)
str(movie.data)
```

#check for missing data
```{r}
colSums(is.na(movie.data))
```

#convert categorical variables
```{r}
movie.data$year <- as.numeric(as.factor(movie.data$year))
movie.data$duration <- as.numeric(as.factor(movie.data$duration))
movie.data$genre1 <- as.numeric(as.factor(movie.data$genre1))
movie.data$genre2 <- as.numeric(as.factor(movie.data$genre2))
movie.data$genre3 <- as.numeric(as.factor(movie.data$genre3))
movie.data$country1 <- as.numeric(as.factor(movie.data$country1))
movie.data
```

#Correlation matrix
```{r}
movie.rating <- (movie.data)
corr <- cor(movie.rating)
ggcorrplot(corr)
corr <- as.table(corr)
```
#normalize data
```{r}
md <- movie.data # copy to your own object

normalize <- function(x) {
  num <- x - min(x)
  denom <- max(x) - min(x)
  return (num/denom)
}

norm.data <- movie.data
norm.data <-as.data.frame(lapply(md, normalize))
head(norm.data)
```


#split into training and testing set 
```{r}
nrow(movie.data)
rows <- c(1:nrow(movie.data))
split <- sample(rows,size = (nrow(movie.data)*0.80))
train <- as.data.frame(movie.data[split,])
#train <- as.data.frame(scale(train1))
test <- as.data.frame(movie.data[-split,])
#test <- as.data.frame(scale(test1))
nrow(train)
head(train)
nrow(test)
head(test)
```

#build the KNN network
```{r}
# Empty variables
pred <- list()
accuracy <- numeric()

# From k=1 to k=100...
for(k in 1:100){
  
  # KnnTestPrediction for each k
  pred[[k]] <- knn(train[,1:6], test[,1:6], train$avg_vote, k, prob=TRUE)
  
  # Accuracy for each k   
  accuracy[k] <- sum(pred[[k]]==test$avg_vote)/length(test$avg_vote)*100
  print(cat(as.character(k) , as.character(accuracy[k])))
}

#find optimal k
index<-which(accuracy %in% max(accuracy))
index<- index[1]
index

# Accuracy vs Choice of k
?plot
plot(accuracy, type="b", col="dodgerblue", 
     xlab="k, number of neighbors", ylab="Classification accuracy", 
     main="Accuracy vs Neighbors")

# Add lines indicating k with best accuracy
abline(v=which(accuracy==max(accuracy)), col="orange", lwd=1.5)

# Add line for max accuracy seen
?abline
abline(h=max(accuracy), col="red", lty=2)
# lty=2 for dashed

# Add line for min accuracy seen 
abline(h=min(accuracy), col="grey", lty=2)

k <- knn(train = train[,1:6], test = test[,1:6], cl = train$avg_vote, k=index)
k <- as.data.frame(k)
#table(test$avg_vote, k1)
#sum(k1==test$avg_vote)/length(test$avg_vote)*100
```

#predict and get error
```{r}
test <- as.data.frame(test)

#pred <- predict(k1, test[,7])
pred<-as.numeric(as.numeric(as.character(sub("," , ".", unlist(k)))))

results2<- data.frame(actual = test$avg_vote, prediction = pred)
results2
paste("RMSE =",RMSE(test$avg_vote, pred))
```



