---
title: "SVM_MOVIEPROJECT"
author: "Whitney Chu"
date: "04/11/2020"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Import libraries
```{r}
library(forecast)
library(tidyverse)    
library(e1071)  
library(RColorBrewer)
library(dplyr)
library(caTools)
library(datasets)
library(neuralnet)
library(caret)
library(reshape2)
library(ggplot2)
library(stringr)
library(nnet)
library(DMwR)
library(mltools)
library(rmarkdown)
library(rpart)
library(rpart.plot)
library(ggcorrplot)
library(randomForest)
library(DMwR)
library(nnet)
```

#Read and Import Data
```{r}
movie.data <- read.csv("ALL_COUNTRIES.csv")
movie.data
```

#Preview the Dataset
```{r}
set.seed(100)
movie.data <- movie.data[sample(nrow(movie.data), 2500),]
movie.data <- movie.data[,c(2,4:7, 9:10)]
movie.data
head(movie.data)
summary(movie.data)
dim(movie.data)
str(movie.data)
```

#check for missing data
```{r}
colSums(is.na(movie.data))
```

# Adding binary, dependent variable for logistic regression analysis
```{r}
movie.data$FavourableMovie <- ifelse(movie.data$imdb_rating>=0.64,1,0)
str(movie.data)
View(movie.data)
```

#convert categorical variables
```{r}
movie.data$show_type <- as.numeric(as.factor(movie.data$show_type))
movie.data$ori_country <- as.numeric(as.factor(movie.data$ori_country))
movie.data$genre <- as.numeric(as.factor(movie.data$genre))
movie.data$year <- as.numeric(as.factor(movie.data$year))
movie.data$is_NF_Ori <- as.numeric(as.factor(movie.data$is_NF_Ori))
movie.data$Continent <- as.numeric(as.factor(movie.data$Continent))
movie.data
```

#Correlation matrix
```{r}
movie.rating <- (movie.data)
corr <- cor(movie.rating)
ggcorrplot(corr)
corr <- as.table(corr)
```

#split into training and testing set 
```{r}
nrow(movie.data)
rows <- c(1:nrow(movie.data))
split <- sample(rows,size = (nrow(movie.data)*0.80))
train <- as.data.frame(movie.data[split,])
test <- as.data.frame(movie.data[-split,])

nrow(train)
head(train)
str(train)
nrow(test)
head(test)
```

#create SVM model 
```{r}
Moviesvm = svm(formula = FavourableMovie ~ show_type + ori_country + genre + year + is_NF_Ori + Continent, data = train, kernel = 'linear')
summary(Moviesvm)
```

#Cross-validation of Cost
```{r}
tune.out=tune(svm ,FavourableMovie~ show_type + ori_country + genre + year + is_NF_Ori + Continent,data=train ,kernel ="linear",k = 5, 
              ranges =list(cost=c(0.001,0.01,0.1, 1.5, 10)))
summary(tune.out)
bestmod =tune.out$best.model
print(bestmod)
optimal_cost <- bestmod$cost
```

#svm model with optimal cost
```{r}
Moviesvm = svm(formula = FavourableMovie ~ show_type + ori_country + genre + year + is_NF_Ori + Continent, data = train, cost = optimal_cost, kernel = 'linear')
summary(Moviesvm)
```

#prediction and error
```{r}
pred.svm <- predict(Moviesvm,test)
pred <- ifelse(pred.svm >=0.64, "1", "0")
mean(test$FavourableMovie!=pred)
table(pred, test$FavourableMovie)
```

#ROC curve
```{r}
plot(roc(test$FavourableMovie, pred.svm, direction="<"),
     col="yellow", lwd=3, main="ROC curve")
```